### ISSUE TITLE
The condition of occuring "TooManyEraStakeValues" Error

### ISSUE THREAD

**Issue by johnnyji-dev** [AstarNetwork/astar-frame#166]
On shibuya Testnet,
I staked some amount for a long time, and than I made about 4 SBY reward on FreeBalance(rewardDestination).

I tried to unstake all staked amount, but my unstaking transaction failed with "TooManyEraStakeValues" Error.

Can I get some condition of occuring "TooManyEraStakeValues" error? like below.
For example, It will occur to try unstaking transaction on over 30era or 1 SBY.

https://shibuya.subscan.io/extrinsic/0xab7dd945baa40159ae062ed19eea8374f5da24663429842c5e21825c2a07ca0f

**Comment by johnnyji-dev** [comment]
I share my test result on that.
--
Network : Shibuya Testnet.
dApp Staking : only 1 dapp
Accumlated Era(Need to Claim Era) : 58 Era

Staking and Unstaking Fail(No Tip).
https://shibuya.subscan.io/account/WKFTYBxLbcG1N5fS7s31U9WRJEZgxEoLCTYHyCq6v867HBb
<img width="1301" alt="6" src="https://github.com/AstarNetwork/astar-frame/assets/125259310/1e9e522d-43d7-40de-bf9f-9ffc87b28f38">
<img width="1199" alt="7" src="https://github.com/AstarNetwork/astar-frame/assets/125259310/e680e5ea-123e-4ff6-b79f-1abb73ffa6f7">
<img width="1235" alt="8" src="https://github.com/AstarNetwork/astar-frame/assets/125259310/f448b477-d4e1-4c41-9bb5-86bb527811d2">

Please check these out and feed back me the condition occuring "TooManyEraStakeValues" Error.
I guess that the Error occurs when a account remains over 58Era to claim.

Thanks~

**Comment by Dinonard** [comment]
This is how internal storage works - we cannot keep indefinite history of how much you had staked/locked in each era.
It's expected behavior.

To fix this, you should claim rewards to free balance until you've cleaned the storage enough for it to allow to create new entries.
You can refer to [THIS](https://github.com/AstarNetwork/Astar/blob/master/pallets/dapps-staking/src/lib.rs#L377) to learn more.
